---
title: "Arboles aleatorios"
author: "Luis Nahuel Fernández y Andrés sandoval"
date: '2022-11-26'
output: 
  rmdformats::robobook:
    code_folding: hide
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
remove(list=ls())
gc()
options(scipen=999)
library(dplyr)
library(here)
library(knitr)
library(ltm)
library(kableExtra)

library(tidyverse)
library(tidymodels)
library(gridExtra)

library(Metrics)
library(randomForest)
library(reldist)

setwd(here())
source("funciones/funciones.r")

usu_individual_T421 <- read.csv("EPH_usu_2do_Trim_2022_txt/usu_individual_T222.txt.txt", sep=";")
usu_individual_T421 %>% filter(ESTADO==1 & CAT_OCUP==3)->usu_individual_T421

usu_individual_T421<-auxiliares(usu_individual_T421)



```

# Solo asalariados

```{r}
baseTrain<-usu_individual_T421 %>% filter(P21>0)
baseActual2<-baseTrain[,c("P21","INF", "CH06","CH04","rol", "rama.eph", "NIVEL_ED", "car2", "AGLOMERADO", "PP07H", "PP07A", "PP07E", "CH03", "CH15", "PP03D", "PP3E_TOT", "CH11", "CH08", "CH09", "PP04C", "CH16")]
m1 <- randomForest(
  formula = P21 ~ .,
  data    = baseActual2
)

varImpPlot(m1, sort=TRUE, n.var=min(30, nrow(m1$importance)),
           type=NULL, class=NULL, scale=TRUE, 
           main=deparse(substitute(m1))) 
```

# Todos los ocupados

```{r}
usu_individual_T421 <- read.csv("EPH_usu_2do_Trim_2022_txt/usu_individual_T222.txt.txt", sep=";")
usu_individual_T421 %>% filter(ESTADO==1)->usu_individual_T421

usu_individual_T421<-auxiliares(usu_individual_T421)

baseTrain<-usu_individual_T421 %>% filter(P21>0)
baseActual2<-baseTrain[,c("P21","INF", "CH06","CH04","rol", "rama.eph", "NIVEL_ED", "car2", "AGLOMERADO", "PP07H", "PP07A", "PP07E", "CH03", "CH15", "PP03D", "PP3E_TOT", "CH11", "CH08", "CH09", "PP04C", "CH16")]
m1 <- randomForest(
  formula = P21 ~ .,
  data    = baseActual2
)

varImpPlot(m1, sort=TRUE, n.var=min(30, nrow(m1$importance)),
           type=NULL, class=NULL, scale=TRUE, 
           main=deparse(substitute(m1))) 
```


```{r iter}



usu_individual_T421 <- read.csv("EPH_usu_2do_Trim_2022_txt/usu_individual_T222.txt.txt", sep=";")
usu_individual_T421 %>% filter(CAT_OCUP==3)->usu_individual_T421

usu_individual_T421<-auxiliares(usu_individual_T421)
usu_individual_T421$rama.eph<-as.factor(usu_individual_T421$rama.eph)

giniTot<-gini(usu_individual_T421$P21, usu_individual_T421$PONDIIO)
tabla_final <- read.csv("metricas/metricasRF.csv")
nI=ncol(tabla_final)-1
for (n in nI:101) {

  asalNulos<-ponerNulos(usu_individual_T421)
  sum(is.na(asalNulos$P21_i))
  baseTrain<-asalNulos %>% filter(!is.na(P21_i))


  baseActual2<-baseTrain[,c("P21_i","INF", "CH06","CH04","rol", "rama.eph", "NIVEL_ED", "car2", "AGLOMERADO", "PP07H", "PP07A", "PP07E", "CH03", "CH15", "PP03D", "PP3E_TOT", "CH11", "CH08", "CH09", "PP04C", "CH16")]

  m1 <- randomForest(
  formula = P21_i ~ .,
  data    = baseActual2
)
  baseTest<-asalNulos %>% filter(is.na(P21_i))

  predict(m1,baseTest)->baseTest$P21_final

  c(baseTrain$P21, baseTest$P21_final)->salarios
  c(baseTrain$PONDIIO, baseTest$PONDIIO)->ponderadores

  gini(salarios,ponderadores)->gini2

  if(n==1){
    sesgo<-c("Bias", "Standard",Metrics::bias( baseTest$P21_final,baseTest$P21))
    GF<-c("Gini", "Standard",gini2-giniTot)
    tabla_final<- rbind(metrics(baseTest,truth=P21, estimate=P21_final),sesgo,GF)

  }else{
    sesgo<-c("Bias", "Standard",Metrics::bias( baseTest$P21_final,baseTest$P21))
    GF<-c("Gini", "Standard",gini2-giniTot)
    tablaActual<-  rbind(metrics(baseTest,truth=P21, estimate=P21_final),sesgo,GF)
    tablaActual[, paste0("prueba_",n)]<-tablaActual[,".estimate"]
    tablaActual[,".estimate"]<-NULL
    tabla_final<- left_join(tabla_final,tablaActual, by=c(".metric",".estimator"))

  }


}

```

```{r error_c_m}

library(vioplot)

res<-as.numeric(t(tabla_final[1,3:102]))
vioplot(res, main="RMSE", col="blue")

```

```{r mae}

library(vioplot)

res<-t(tabla_final[3,3:102])
names(res)<-c("RL")
vioplot(res, main="MAE", col="blue")

```

```{r R2}


res<-t(tabla_final[2,3:102])
vioplot(res, main="R2", col="blue")

```

```{r sesgo}


res<-as.numeric(t(tabla_final[4,3:102]))
vioplot(res, main="BIAS", col="blue")

```

```{r gini}


res<-as.numeric(t(tabla_final[5,3:102]))
vioplot(res, main="Indice de GINI", col="blue")

```

```{r}
boxp2<-data.frame(cbind(baseTest$P21_final,
                        baseTest$P21))

names(boxp2)<-c("Predicha", "original")



library(RColorBrewer)

library(vioplot)
vioplot(boxp2,
        col = brewer.pal(n=3, name="Set3"),
        ylab="$", xlab="")
```



```{r}


vioplot(boxp2,
        col = brewer.pal(n=3, name="Set3"),
        ylab="$", xlab="", ylim=c(0,20000))
```

```{r}

vioplot(baseTrain$P21)
```

