---
title: "Regresión Lasso"
author: "Luis Nahuel Fernández y Andrés sandoval"
date: '2022-11-26'
output: html_document
---


# Regresión por Cuantiles


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
remove(list=ls())
gc()
library(here)
library(dplyr)
library(tidyverse)
library(tidymodels)
library(vctrs)
library(quantreg)
library(dplyr)



setwd(here())
source("funciones\\funciones.r")

usu_individual_T421 <- read.csv("EPH_usu_2do_Trim_2022_txt\\usu_individual_T222.txt.txt", sep=";")
usu_individual_T421 %>% filter(ESTADO==1 & CAT_OCUP==3)->usu_individual_T421

usu_individual_T421<-auxiliares(usu_individual_T421)
usu_individual_T421$rama.eph<-as.factor(usu_individual_T421$rama.eph)

head(usu_individual_T421)


```


```{r , include=TRUE}


knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)

for (n in 1:3) {
  
  asalNulos<-ponerNulos(usu_individual_T421)
  sum(is.na(asalNulos$P21_i))
  asalNulos$Y <- log(asalNulos$P21_i)
  baseTrain<-asalNulos %>% filter(!is.na(Y))
  # Consideramos un percentil de 0.9
  modelo <- rq( Y ~ INF + CH06 + CH04 +rol+ rama.eph+ car2+AGLOMERADO+INTENSI, data=baseTrain, tau = 0.9)
  
  baseTest<-asalNulos %>% filter(is.na(Y))

  baseTest$fitted_exp<-exp(predict(modelo, baseTest))

  if(n==1){
    sesgo<-c("Bias", "Standard",Metrics::bias(baseTest$P21, baseTest$fitted_exp))
    tabla_final<- rbind(metrics(baseTest,truth=P21, estimate=fitted_exp),sesgo)

  }else{
    sesgo<-c("Bias", "Standard",Metrics::bias(baseTest$P21, baseTest$fitted_exp))
    tablaActual<-  rbind(metrics(baseTest,truth=P21, estimate=fitted_exp),sesgo)
    tablaActual[, paste0("prueba_",n)]<-tablaActual[,".estimate"]
    tablaActual[,".estimate"]<-NULL
    tabla_final<- left_join(tabla_final,tablaActual, by=c(".metric",".estimator"))

  }
}


```

# ¿ Como modifican estos algoritmos la distribución de los ingresos?


## Modelo a nivel 0.9



```{r , out.width="100%", include=TRUE}


knitr::opts_chunk$set(echo = FALSE)


train_09 <-usu_individual_T421 %>% filter(P21>0)

train_09$Y <- log(train_09$P21)

modelo <- rq( Y ~ INF + CH06 + CH04 +rol+ rama.eph+ car2+AGLOMERADO+INTENSI, data=train_09, tau = 0.9)

train_09$pred <- exp(predict(modelo, train_09[, c("INF", "CH06", "CH04", "rol", "rama.eph", "car2", "AGLOMERADO", "INTENSI")]))


boxplot(train_09[, c("pred", "P21")])
```

## Modelo a nivel 0.2


```{r , out.width="100%", include=TRUE}


knitr::opts_chunk$set(echo = FALSE)


train_02 <-usu_individual_T421 %>% filter(P21>0)

train_02$Y <- log(train_02$P21)

modelo <- rq( Y ~ INF + CH06 + CH04 +rol+ rama.eph+ car2+AGLOMERADO+INTENSI, data=train_02, tau = 0.25)

train_02$pred <- exp(predict(modelo, train_02[, c("INF", "CH06", "CH04", "rol", "rama.eph", "car2", "AGLOMERADO", "INTENSI")]))


boxplot(train_02[, c("pred", "P21")])
```

